name: "Git-Push-metadata-action"
author: "@ZeitounCorp"
description: "Github action that should execute when a new push happens on a repository, should alert the maintainer by mail with the number of files modified, number of modifications, full date (DD/MM/YYYY @ time) and the commit message"
inputs:
  owner:
    description: "The owner of the repository"
    required: true
  push_user:
    description: "The user that pushed the commit"
    required: true
  repo:
    description: "The name of the repository"
    required: true
  push_id:
    description: "The id of the push"
    required: true
  commit_sha:
    description: "The commit sha"
    required: true
  commit_message:
    description: "The commit message"
    required: true
  ref:
    description: "The ref of the push"
    required: true
  token:
    description: "The token to use to access the GitHub API"
    required: true
  receivers: 
    description: "The list of receivers to send the mail to"
    required: true
  mailer_password:
    description: "The password of the mailer"
    required: true
  mailer_sender:
    description: "The sender of the mail"
    required: true
  nodemailer_host:
    description: "The host of the mailer"
    required: true
  nodemailer_port:
    description: "The port of the mailer"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
