name: Git commit metadata annotation

on: push

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    name: Annotates commits with metadata
    steps:
      - uses: hmarr/debug-action@v2
      - name: Annotate Commit
        uses: ZeitounCorp/Git-Push-metadata-action@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          push_user: ${{ github.event.sender.login }}
          commit_sha: ${{ github.event.after }}
          ref: ${{ github.event.ref }}
          commit_message: ${{ github.event.commits[0].message }}
          push_id: ${{ github.event.commits[0].id }}
          token: ${{ secrets.GITHUB_TOKEN }}
